### ISSUE TITLE
Error failed finding property `state`

### ISSUE THREAD

**Issue by lalelunet** [TobseF/impf-bot#53]
In the latest docker image I get a error at start of the chrome browser. 

REPOSITORY                     TAG       IMAGE ID       CREATED        SIZE
pfuenzle/impf-bot              latest    096573139298   4 hours ago    2.58GB

edit the location to just the plz or remove a second location does not help. Switching back to the version 1.2 does resolve the problem.

pfuenzle/impf-bot              v1.2      ced83d6c9ec6   10 days ago    2.7GB

<img width="973" alt="Bildschirmfoto 2021-05-17 um 18 47 49" src="https://user-images.githubusercontent.com/4786404/118529550-ee155780-b743-11eb-81a3-de4d5ea2f625.png">

**Comment by Pfuenzle** [comment]
This is due to a new update of the bot, which is looking for a new attribute in your config file.
If you add:

`state = Baden-Württemberg`

To your config file, the error is resolved (replace Baden-Württemberg with the state youre searching in).
In v1.2, the state function was not coded into the bot, which is why it is working without it

**Comment by lalelunet** [comment]
You are right. Adding the parameter state to the config resolve the pro problem. Thank you for your fast response and the good project :)
