### ISSUE TITLE
Installing problems

### ISSUE THREAD

**Issue by chim0rin** [TobseF/impf-bot#6]
I have problems installing the ChromeDriver and Google Chrome.

Your program expects "chromedriver.exe" in
`C:\ProgramData\chocolatey\lib\chromedriver\tools`
whereas it is located at
`C:\tools\selenium\`.
A simple Copy&Paste solves this problem for me (At least I think so).

My second problem is Google Chrome. I can`t choose the directory it will be installed in, so Google Chrome installs itself in

`C:\Program Files\Google\Chrome\Application\`.

According to [Github ChromeDriver](https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver) expects it in
`C:\Users\%USERNAME%\AppData\Local\Google\Chrome\Application\chrome.exe`.
Without moving the files, your program (or selenium) can`t find Chrome. If I move the files, "chrome.exe" gets found, but crashes instantly.

Am I missing something?

**Comment by TobseF** [comment]
The `chromedriver.exe` can be installed anywhere, because you can configure the path in the 
`src/main/resources/config.properties`

```properties
# Chrome Driver
pathDriver = C:/ProgramData/chocolatey/lib/chromedriver/tools/
nameDriver = webdriver.chrome.driver
exeDriver = chromedriver.exe
```

In my setup Chrome ins installed in the default location in:  
`C:\Program Files\Google\Chrome\Application\chrome.exe`
The `%USERNAME%\AppData` is only used If you install it without admin rights.
In this `Program Files` location the Chrome Driver find's Chrome by its own.

If this doesn't work for you, you can gets your hands dirty and set it in the code by
```java
ChromeOptions options = new ChromeOptions();
options.setBinary("/path/to/other/chrome/binary");
```
| [Using-a-Chrome-executable-in-a-non-standard-location](https://sites.google.com/a/chromium.org/chromedriver/capabilities#TOC-Using-a-Chrome-executable-in-a-non-standard-location)
